name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out the sections below to help us reproduce and fix the issue.

  - type: input
    id: version
    attributes:
      label: Library Version
      description: Which version of logback-access-spring-boot-starter are you using?
      placeholder: "e.g., 1.0.0"
    validations:
      required: true

  - type: dropdown
    id: server
    attributes:
      label: Embedded Server
      description: Which embedded server are you using?
      options:
        - Tomcat
        - Jetty
    validations:
      required: true

  - type: input
    id: spring-boot-version
    attributes:
      label: Spring Boot Version
      placeholder: "e.g., 4.0.2"
    validations:
      required: true

  - type: input
    id: java-version
    attributes:
      label: Java Version
      placeholder: "e.g., 21"
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: logback-access.xml Configuration
      description: Paste your logback-access.xml configuration file
      render: xml
    validations:
      required: false

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Describe the steps to reproduce the issue
      placeholder: |
        1. Configure logback-access with ...
        2. Send a request to ...
        3. Observe ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened? Include error messages or stack traces if applicable.
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information that might be helpful (logs, screenshots, related issues, etc.)
    validations:
      required: false
