name: Feature Request
description: Suggest a new feature or enhancement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Please describe the problem you're trying to solve and your proposed solution.

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: What problem does this feature solve? Describe the scenario where you need this.
      placeholder: "When I try to ..., I need ..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this feature work? Include configuration examples if applicable.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches have you considered? Why are they insufficient?
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information, references, or screenshots.
    validations:
      required: false
